package com.seckill.dataobject;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbg.generated Tue Apr 13 10:49:31 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encrpt_passwod
     *
     * @mbg.generated Tue Apr 13 10:49:31 CST 2021
     */
    private String encrptPasswod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbg.generated Tue Apr 13 10:49:31 CST 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbg.generated Tue Apr 13 10:49:31 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbg.generated Tue Apr 13 10:49:31 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encrpt_passwod
     *
     * @return the value of user_password.encrpt_passwod
     *
     * @mbg.generated Tue Apr 13 10:49:31 CST 2021
     */
    public String getEncrptPasswod() {
        return encrptPasswod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encrpt_passwod
     *
     * @param encrptPasswod the value for user_password.encrpt_passwod
     *
     * @mbg.generated Tue Apr 13 10:49:31 CST 2021
     */
    public void setEncrptPasswod(String encrptPasswod) {
        this.encrptPasswod = encrptPasswod == null ? null : encrptPasswod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.user_id
     *
     * @return the value of user_password.user_id
     *
     * @mbg.generated Tue Apr 13 10:49:31 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.user_id
     *
     * @param userId the value for user_password.user_id
     *
     * @mbg.generated Tue Apr 13 10:49:31 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}